name: push on server
on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-20.04
    steps:
      - name: "set ssh keys"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: "deploy on server"
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd apps
            cd mariam-revia-epic-movie-quotes-api
            git pull
            npm ci
            npm run build
          EOF
